# Generated by Django 5.0.2 on 2024-05-04 11:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0006_internship_my_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="internship",
            name="mob_no",
            field=models.CharField(default=True, max_length=60),
        ),
    ]
