# Generated by Django 5.0.2 on 2024-05-04 11:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0007_internship_mob_no"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="internship",
            name="mob_no",
        ),
        migrations.AddField(
            model_name="internship",
            name="phone_no",
            field=models.CharField(default=True, max_length=10),
        ),
    ]
