# Generated by Django 5.0.2 on 2024-05-08 13:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0009_remove_internship_phone_no_internship_phonenumber"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="internship",
            name="phonenumber",
        ),
        migrations.AddField(
            model_name="internship",
            name="phone_no",
            field=models.CharField(default=True, max_length=10),
        ),
    ]
